/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProfileManager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Profile;
import model.ProfileDirectory;

/**
 *
 * @author tirthnaik
 */
public class ViewProfileJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private ProfileDirectory profileDirectory;
    private Profile profile;
    /**
     * Creates new form ViewProfileJPanel
     */
    public ViewProfileJPanel(JPanel userProcessContainer, ProfileDirectory directory, Profile profile) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.profile = profile;
        
        refreshTextFields();
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewBack = new javax.swing.JButton();
        lblViewTitle = new javax.swing.JLabel();
        txtViewSsn = new javax.swing.JTextField();
        lblViewLastName = new javax.swing.JLabel();
        lblViewGender = new javax.swing.JLabel();
        lblViewPhoneNumber = new javax.swing.JLabel();
        lblViewFirstName = new javax.swing.JLabel();
        lblViewNationality = new javax.swing.JLabel();
        lblViewDateOfBirth = new javax.swing.JLabel();
        txtViewLastName = new javax.swing.JTextField();
        lblViewEmail = new javax.swing.JLabel();
        txtViewEmail = new javax.swing.JTextField();
        txtViewGender = new javax.swing.JTextField();
        lblViewSsn = new javax.swing.JLabel();
        txtViewPhoneNumber = new javax.swing.JTextField();
        txtViewFirstName = new javax.swing.JTextField();
        txtViewNationality = new javax.swing.JTextField();
        txtViewDateOfBirth = new javax.swing.JTextField();
        ViewHomeAddressJPanel = new javax.swing.JPanel();
        lblViewHomeTitle = new javax.swing.JLabel();
        lblViewHomeAddress1 = new javax.swing.JLabel();
        lblViewHomeAddress2 = new javax.swing.JLabel();
        lblViewHomeCity = new javax.swing.JLabel();
        lblViewHomeState = new javax.swing.JLabel();
        lblViewHomeZip = new javax.swing.JLabel();
        lblViewCountry = new javax.swing.JLabel();
        txtViewHomeAddress1 = new javax.swing.JTextField();
        txtViewHomeAddress2 = new javax.swing.JTextField();
        txtViewHomeCity = new javax.swing.JTextField();
        txtViewHomeState = new javax.swing.JTextField();
        txtViewHomeZip = new javax.swing.JTextField();
        txtViewHomeCountry = new javax.swing.JTextField();
        ViewWorkAddressJPanel = new javax.swing.JPanel();
        lblViewWorKTitle = new javax.swing.JLabel();
        lblViewWorkAddress1 = new javax.swing.JLabel();
        lblViewWorkAddress2 = new javax.swing.JLabel();
        lblViewWorkcity = new javax.swing.JLabel();
        lblViewWorkState = new javax.swing.JLabel();
        lblViewWorkZip = new javax.swing.JLabel();
        lblViewWorkCountry = new javax.swing.JLabel();
        txtViewWorkAddress1 = new javax.swing.JTextField();
        txtViewWorkAddress2 = new javax.swing.JTextField();
        txtViewWorkCity = new javax.swing.JTextField();
        txtViewWorkState = new javax.swing.JTextField();
        txtViewWorkZip = new javax.swing.JTextField();
        txtViewWorkCountry = new javax.swing.JTextField();
        btnViewSave = new javax.swing.JButton();
        btnViewUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        btnViewBack.setText("<<< Back");
        btnViewBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBackActionPerformed(evt);
            }
        });

        lblViewTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblViewTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewTitle.setText("View Profile");

        lblViewLastName.setText("Last Name");

        lblViewGender.setText("Gender");

        lblViewPhoneNumber.setText("Phone Number");

        lblViewFirstName.setText("First Name");

        lblViewNationality.setText("Nationality");

        lblViewDateOfBirth.setText("Date of Birth");

        lblViewEmail.setText("Email");

        txtViewGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewGenderActionPerformed(evt);
            }
        });

        lblViewSsn.setText("SSN");

        txtViewFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewFirstNameActionPerformed(evt);
            }
        });

        ViewHomeAddressJPanel.setBackground(new java.awt.Color(255, 255, 204));

        lblViewHomeTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblViewHomeTitle.setText("HOME ADDRESS");

        lblViewHomeAddress1.setText("Address1");

        lblViewHomeAddress2.setText("Address2");

        lblViewHomeCity.setText("City");

        lblViewHomeState.setText("State");

        lblViewHomeZip.setText("Zip");

        lblViewCountry.setText("Country");

        txtViewHomeAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewHomeAddress1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewHomeAddressJPanelLayout = new javax.swing.GroupLayout(ViewHomeAddressJPanel);
        ViewHomeAddressJPanel.setLayout(ViewHomeAddressJPanelLayout);
        ViewHomeAddressJPanelLayout.setHorizontalGroup(
            ViewHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewHomeAddressJPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblViewHomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewHomeAddressJPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(ViewHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewHomeAddressJPanelLayout.createSequentialGroup()
                        .addComponent(lblViewCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewHomeCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewHomeAddressJPanelLayout.createSequentialGroup()
                        .addComponent(lblViewHomeZip, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewHomeZip, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ViewHomeAddressJPanelLayout.createSequentialGroup()
                            .addComponent(lblViewHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtViewHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ViewHomeAddressJPanelLayout.createSequentialGroup()
                            .addComponent(lblViewHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtViewHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ViewHomeAddressJPanelLayout.createSequentialGroup()
                            .addComponent(lblViewHomeAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtViewHomeAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ViewHomeAddressJPanelLayout.createSequentialGroup()
                            .addComponent(lblViewHomeAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtViewHomeAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );
        ViewHomeAddressJPanelLayout.setVerticalGroup(
            ViewHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewHomeAddressJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewHomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(ViewHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewHomeAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViewHomeAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ViewHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewHomeAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViewHomeAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtViewHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtViewHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewHomeZip, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViewHomeZip, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViewHomeCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        ViewWorkAddressJPanel.setBackground(new java.awt.Color(204, 204, 255));

        lblViewWorKTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblViewWorKTitle.setText("WORK ADDRESS");

        lblViewWorkAddress1.setText("Address1");

        lblViewWorkAddress2.setText("Address2");

        lblViewWorkcity.setText("City");

        lblViewWorkState.setText("State");

        lblViewWorkZip.setText("Zip");

        lblViewWorkCountry.setText("Country");

        txtViewWorkAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewWorkAddress1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewWorkAddressJPanelLayout = new javax.swing.GroupLayout(ViewWorkAddressJPanel);
        ViewWorkAddressJPanel.setLayout(ViewWorkAddressJPanelLayout);
        ViewWorkAddressJPanelLayout.setHorizontalGroup(
            ViewWorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewWorkAddressJPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblViewWorKTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewWorkAddressJPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(ViewWorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewWorkAddressJPanelLayout.createSequentialGroup()
                        .addComponent(lblViewWorkCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewWorkCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewWorkAddressJPanelLayout.createSequentialGroup()
                        .addComponent(lblViewWorkZip, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewWorkZip, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewWorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ViewWorkAddressJPanelLayout.createSequentialGroup()
                            .addComponent(lblViewWorkState, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtViewWorkState, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ViewWorkAddressJPanelLayout.createSequentialGroup()
                            .addComponent(lblViewWorkcity, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtViewWorkCity, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ViewWorkAddressJPanelLayout.createSequentialGroup()
                            .addComponent(lblViewWorkAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtViewWorkAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ViewWorkAddressJPanelLayout.createSequentialGroup()
                            .addComponent(lblViewWorkAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtViewWorkAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );
        ViewWorkAddressJPanelLayout.setVerticalGroup(
            ViewWorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewWorkAddressJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewWorKTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(ViewWorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewWorkAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViewWorkAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ViewWorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewWorkAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViewWorkAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewWorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtViewWorkCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewWorkcity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewWorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtViewWorkState, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewWorkState, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewWorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewWorkZip, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViewWorkZip, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewWorkAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewWorkCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViewWorkCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnViewSave.setText("Save");
        btnViewSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSaveActionPerformed(evt);
            }
        });

        btnViewUpdate.setText("Update");
        btnViewUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewBack, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblViewTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(btnViewSave, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btnViewUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblViewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtViewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblViewDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtViewDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblViewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtViewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblViewSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtViewSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(74, 74, 74)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblViewLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblViewGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblViewPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(lblViewNationality, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtViewLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtViewGender, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtViewPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtViewNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(ViewHomeAddressJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(94, 94, 94)
                            .addComponent(ViewWorkAddressJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(121, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 675, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblViewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtViewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblViewLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtViewLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblViewDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtViewDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblViewGender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtViewGender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblViewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtViewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblViewPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtViewPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblViewSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtViewSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblViewNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtViewNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ViewHomeAddressJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewWorkAddressJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(115, 115, 115)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtViewGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewGenderActionPerformed

    private void txtViewFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewFirstNameActionPerformed

    private void txtViewHomeAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewHomeAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewHomeAddress1ActionPerformed

    private void txtViewWorkAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewWorkAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewWorkAddress1ActionPerformed

    private void btnViewUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUpdateActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_btnViewUpdateActionPerformed

    private void btnViewSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSaveActionPerformed
        // TODO add your handling code here:
        String firstName = txtViewFirstName.getText();
        String lastName = txtViewLastName.getText();
        String dateOfBirth = txtViewDateOfBirth.getText();
        String gender = txtViewGender.getText();
        String email = txtViewEmail.getText();
        String ssn = txtViewSsn.getText();
        String phoneNumber = txtViewPhoneNumber.getText();
        String nationality = txtViewNationality.getText();
        String homeAddress1 = txtViewHomeAddress1.getText();
        String homeAddress2 = txtViewHomeAddress2.getText();
        String homeCity = txtViewHomeCity.getText();
        String homeState = txtViewHomeState.getText(); 
        String homeCountry = txtViewHomeCountry.getText();
        String homeZip = txtViewHomeZip.getText();
        String workAddress1 = txtViewWorkAddress1.getText();
        String workAddress2 = txtViewWorkAddress2.getText();
        String workCity = txtViewWorkCity.getText();
        String workState = txtViewWorkState.getText();
        String workCountry = txtViewWorkCountry.getText();
        String workZip = txtViewWorkZip.getText();
        
        if (firstName.isBlank() || lastName.isBlank() || dateOfBirth.isBlank() || gender.isBlank() || email.isBlank() || phoneNumber.isBlank() || ssn.isBlank() || nationality.isBlank() || 
                homeAddress1.isBlank() || homeAddress2.isBlank() || homeCity.isBlank() || homeState.isBlank() || homeZip.isBlank() || homeCountry.isBlank() || workAddress1.isBlank() || workAddress2.isBlank() || 
                workCity.isBlank() || workState.isBlank() || workZip.isBlank() || workCountry.isBlank()){
            JOptionPane.showMessageDialog(null,"All Fields are mandatory");
            
            return;
        }
        
        profile.setFirstName(firstName);
        profile.setLastName(lastName);
        profile.setDateOfBirth(dateOfBirth);
        profile.setGender(gender);
        profile.setEmail(email);
        profile.setSsn(ssn);
        profile.setNationality(nationality);
        profile.setHomeAddress1(homeAddress1);
        profile.setHomeAddress2(homeAddress2);
        profile.setHomeCity(homeCity);
        profile.setHomeState(homeState);
        profile.setHomeCountry(homeCountry);
        profile.setWorkAddress1(workAddress1);
        profile.setWorkAddress2(workAddress2);
        profile.setWorkCity(workCity);
        profile.setWorkState(workState);
        profile.setWorkCountry(workCountry);
        profile.setHomeZip(homeZip);
        profile.setWorkZip(workCity);
        profile.setPhoneNumber(phoneNumber);
        JOptionPane.showMessageDialog(this, "Profile successfully updated", "Warning", JOptionPane.WARNING_MESSAGE);
        setViewMode();
    }//GEN-LAST:event_btnViewSaveActionPerformed

    private void btnViewBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] panelStack = userProcessContainer.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length -1];
        ManageProfileJPanel manageProfileJPanel = (ManageProfileJPanel) lastPanel;
        manageProfileJPanel.populateTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        
    }//GEN-LAST:event_btnViewBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViewHomeAddressJPanel;
    private javax.swing.JPanel ViewWorkAddressJPanel;
    private javax.swing.JButton btnViewBack;
    private javax.swing.JButton btnViewSave;
    private javax.swing.JButton btnViewUpdate;
    private javax.swing.JLabel lblViewCountry;
    private javax.swing.JLabel lblViewDateOfBirth;
    private javax.swing.JLabel lblViewEmail;
    private javax.swing.JLabel lblViewFirstName;
    private javax.swing.JLabel lblViewGender;
    private javax.swing.JLabel lblViewHomeAddress1;
    private javax.swing.JLabel lblViewHomeAddress2;
    private javax.swing.JLabel lblViewHomeCity;
    private javax.swing.JLabel lblViewHomeState;
    private javax.swing.JLabel lblViewHomeTitle;
    private javax.swing.JLabel lblViewHomeZip;
    private javax.swing.JLabel lblViewLastName;
    private javax.swing.JLabel lblViewNationality;
    private javax.swing.JLabel lblViewPhoneNumber;
    private javax.swing.JLabel lblViewSsn;
    private javax.swing.JLabel lblViewTitle;
    private javax.swing.JLabel lblViewWorKTitle;
    private javax.swing.JLabel lblViewWorkAddress1;
    private javax.swing.JLabel lblViewWorkAddress2;
    private javax.swing.JLabel lblViewWorkCountry;
    private javax.swing.JLabel lblViewWorkState;
    private javax.swing.JLabel lblViewWorkZip;
    private javax.swing.JLabel lblViewWorkcity;
    private javax.swing.JTextField txtViewDateOfBirth;
    private javax.swing.JTextField txtViewEmail;
    private javax.swing.JTextField txtViewFirstName;
    private javax.swing.JTextField txtViewGender;
    private javax.swing.JTextField txtViewHomeAddress1;
    private javax.swing.JTextField txtViewHomeAddress2;
    private javax.swing.JTextField txtViewHomeCity;
    private javax.swing.JTextField txtViewHomeCountry;
    private javax.swing.JTextField txtViewHomeState;
    private javax.swing.JTextField txtViewHomeZip;
    private javax.swing.JTextField txtViewLastName;
    private javax.swing.JTextField txtViewNationality;
    private javax.swing.JTextField txtViewPhoneNumber;
    private javax.swing.JTextField txtViewSsn;
    private javax.swing.JTextField txtViewWorkAddress1;
    private javax.swing.JTextField txtViewWorkAddress2;
    private javax.swing.JTextField txtViewWorkCity;
    private javax.swing.JTextField txtViewWorkCountry;
    private javax.swing.JTextField txtViewWorkState;
    private javax.swing.JTextField txtViewWorkZip;
    // End of variables declaration//GEN-END:variables

    private void refreshTextFields() {
        
        txtViewFirstName.setText(profile.getFirstName());
        txtViewLastName.setText(profile.getLastName());
        txtViewDateOfBirth.setText(profile.getDateOfBirth());
        txtViewGender.setText(profile.getGender());
        txtViewEmail.setText(profile.getEmail());
        txtViewPhoneNumber.setText(profile.getPhoneNumber());
        txtViewSsn.setText(profile.getSsn());
        txtViewNationality.setText(profile.getNationality());
        txtViewHomeAddress1.setText(profile.getHomeAddress1());
        txtViewHomeAddress2.setText(profile.getHomeAddress2());
        txtViewHomeCity.setText(profile.getHomeCity());
        txtViewHomeState.setText(profile.getHomeState());
        txtViewHomeZip.setText(profile.getHomeZip());
        txtViewHomeCountry.setText(profile.getHomeCountry());
        txtViewWorkAddress1.setText(profile.getWorkAddress1());
        txtViewWorkAddress2.setText(profile.getWorkAddress2());
        txtViewWorkCity.setText(profile.getHomeCity());
        txtViewWorkState.setText(profile.getWorkState());
        txtViewWorkZip.setText(profile.getWorkZip());
        txtViewWorkCountry.setText(profile.getWorkCountry());
    }

    private void setViewMode() {
        txtViewFirstName.setEnabled(false);
        txtViewLastName.setEnabled(false);
        txtViewDateOfBirth.setEnabled(false);
        txtViewGender.setEnabled(false);
        txtViewEmail.setEnabled(false);
        txtViewPhoneNumber.setEnabled(false);
        txtViewSsn.setEnabled(false);
        txtViewNationality.setEnabled(false);
        txtViewHomeAddress1.setEnabled(false);
        txtViewHomeAddress2.setEnabled(false);
        txtViewHomeCity.setEnabled(false);
        txtViewHomeState.setEnabled(false);
        txtViewHomeZip.setEnabled(false);
        txtViewHomeCountry.setEnabled(false);
        txtViewWorkAddress1.setEnabled(false);
        txtViewWorkAddress2.setEnabled(false);
        txtViewWorkCity.setEnabled(false);
        txtViewWorkState.setEnabled(false);
        txtViewWorkZip.setEnabled(false);
        txtViewWorkCountry.setEnabled(false);
        
        btnViewSave.setEnabled(false);
        btnViewUpdate.setEnabled(true);
    }
    
    private void setEditMode(){
        
        txtViewFirstName.setEnabled(true);
        txtViewLastName.setEnabled(true);
        txtViewDateOfBirth.setEnabled(true);
        txtViewGender.setEnabled(true);
        txtViewEmail.setEnabled(true);
        txtViewPhoneNumber.setEnabled(true);
        txtViewSsn.setEnabled(true);
        txtViewNationality.setEnabled(true);
        txtViewHomeAddress1.setEnabled(true);
        txtViewHomeAddress2.setEnabled(true);
        txtViewHomeCity.setEnabled(true);
        txtViewHomeState.setEnabled(true);
        txtViewHomeZip.setEnabled(true);
        txtViewHomeCountry.setEnabled(true);
        txtViewWorkAddress1.setEnabled(true);
        txtViewWorkAddress2.setEnabled(true);
        txtViewWorkCity.setEnabled(true);
        txtViewWorkState.setEnabled(true);
        txtViewWorkZip.setEnabled(true);
        txtViewWorkCountry.setEnabled(true);
        
        btnViewSave.setEnabled(true);
        btnViewUpdate.setEnabled(false);
    }
}
